[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "infty"
version = "0.1.2"
description = "A continual learning optimizer and visualization toolkit"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "taofeng weili", email = "ymjiii98@gmail.com"}
]
keywords = ["optimization", "visualization", "machine learning", "deep learning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    'torch>=2.4.0',
    'torchvision',
    'numpy',
    'matplotlib',
    'scipy',
    'seaborn',
    'tqdm',
]

[project.urls]
Homepage = "https://github.com/THUDM/INFTY"
Documentation = "https://infty-ai.github.io/doc/"
Repository = "https://github.com/THUDM/INFTY"
Issues = "https://github.com/THUDM/INFTY/issues"

[project.optional-dependencies]
examples = [
    "easydict",
    "Pillow",
    "PyYAML",
    "scikit-learn",
    "timm==0.6.13",
    "umap-learn",
]


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
